### ISSUE TITLE
Contact me

### ISSUE THREAD

**Issue by Hari-Pi** [animegamer4422/Test-Anime-Site#3]
I can't use GitHub as a messaging app

I'd like to chat with you or have some kind of contact

**Comment by Hari-Pi** [comment]
@YellowGreg

**Comment by YellowGreg** [comment]
@animegamer4422 i could use discord my username is yellowgreg

**Comment by Hari-Pi** [comment]
@YellowGreg  Just sent you a friend request

**Comment by Hari-Pi** [comment]
@YellowGreg 
Waiting for confirmation
